{
    'name': 'Crypto Payment Sync',
    'version': '19.0.0.1',
    'summary': 'Integrate Crypto Payments with Odoo 19 E-commerce & Sales & POS & Accounting',
    'author': 'Bahey Wadea',
    'website': 'https://www.linkedin.com/in/baheywadeahakim/',
    "maintainer": "Bahey Wadea",
    'category': 'Accounting/Payment Acquirers',
    'depends': ['account', 'website_sale', 'payment'],
    'data': [
        'data/crypto_groups.xml',
        'security/ir.model.access.csv',
        'data/payment_method_data.xml',
        'views/payment_crypto_templates.xml',
        'data/payment_provider_data.xml',
        'data/crypto_blockchain_data.xml',
        'data/crypto_network_data.xml',
        'data/cron.xml',
        'views/crypto_currency_views.xml',
        'views/crypto_transaction_views.xml',
        'views/crypto_payment_provider_views.xml',
        'views/crypto_blockchain_views.xml',
        'views/crypto_network_views.xml',
        'views/crypto_wallet_views.xml',
        'views/crypto_wallet_address_views.xml',
        'views/crypto_transaction_evm_views.xml',
        'views/crypto_wallet_address_event_views.xml',
        'views/crypto_accounting_support_views.xml',
        'views/crypto_menu.xml',
        'views/res_partner_views.xml',
        'views/account_journal_views.xml',
        'views/account_payment_views.xml',
    ],
    "assets": {
             'web.assets_frontend': [
                'crypto_payment_sync/static/src/js/crypto_payment_page.js',
            ],
        },
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
    'license': 'LGPL-3',
    'currency': 'USD',
    'price': '6000',
    'images':['static/description/thumbnail.png'],
}
